site_name: mystery-planet
site_description: Life on Mystery Planet
repo_url: https://github.com/mathuv/mystery-planet
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/mathuv">mathuv</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
