# Generated by Django 3.1.7 on 2021-04-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_favouritefoods_food_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable')], max_length=50),
        ),
    ]
