# Generated by Django 3.1.7 on 2021-04-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20210405_2117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritefoods',
            unique_together={('person', 'food')},
        ),
    ]
