# Generated by Django 3.1.7 on 2021-04-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20210406_0217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('person', 'friend')},
        ),
    ]
