# Generated by Django 3.1.7 on 2021-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20210406_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='favourite_foods',
            field=models.ManyToManyField(to='persons.Food'),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to='persons.Person'),
        ),
    ]
